apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-class-vol
  labels:
    app: dep-class-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-class-vol
  template:
    metadata:
      labels:
        app: pod-class-vol
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        volumeMounts:
        - name: class-vol
          mountPath: /input
      volumes:
      - name: class-vol
        persistentVolumeClaim:
          claimName: pvc-class-vol-claim
        # emptyDir: {}
        # hostPath:
        #   path: /var/data          