apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/pv1


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-volume
# spec:
#   capacity:
#     storage: 10Gi
  # volumeMode: Filesystem
  # accessModes:
  # - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  # storageClassName: local-storage
  # local:
  #   path: /mnt/disk/ssd1
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - example-node