apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
 # namespace: web
spec:
  # storageClassName: manual
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi